name: Dry run docling-serve image building

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
      - id: set
        run: echo "matrix=$(jq -c . .github/image-matrix.json)" >> "$GITHUB_OUTPUT"

  build_image:
    name: Build ${{ matrix.spec.name }} container image
    needs: prepare
    strategy:
      matrix:
        spec: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    uses: ./.github/workflows/job-image.yml
    with:
      publish: false
      build_args: ${{ matrix.spec.build_args }}
      ghcr_image_name: ${{ matrix.spec.name }}
      quay_image_name: ""
      platforms: ${{ matrix.spec.platforms }}
      tag_latest: ${{ matrix.spec.tag_latest }}
